# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Arcivo (one-folder build with two executables sharing one runtime):
#   dist/Arcivo/Arcivo.exe            – console app: interactive home screen (no args) + full CLI (with args)
#   dist/Arcivo/ArcivoDashboard.exe   – windowed desktop app (the dashboard)
# Build:  pyinstaller packaging/pyinstaller/arcivo.spec --noconfirm --clean
import re
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

ROOT = Path(SPECPATH).resolve().parents[1]  # noqa: F821 (SPECPATH is injected by PyInstaller)
SRC = ROOT / "src"
BRAND = SRC / "arcivo" / "assets" / "brand"
VERSION = re.search(r'__version__ = "([^"]+)"', (SRC / "arcivo" / "__version__.py").read_text()).group(1)

datas = collect_data_files("arcivo", includes=["db/migrations/*.sql", "i18n/locales/*.json", "assets/**/*", "export/templates/*"])
datas += [(str(ROOT / "LICENSE"), "."), (str(ROOT / "THIRD_PARTY_NOTICES.md"), ".")]
hidden = (collect_submodules("arcivo") + collect_submodules("telethon.tl") + collect_submodules("python_socks")
          + ["keyring.backends.Windows", "win32ctypes.core", "telethon.network.connection.tcpmtproxy"])

# Modules Arcivo never uses (unused Qt add-ons, Pillow, numpy) – keeps the bundle small.
EXCLUDES = [
    "tkinter", "PIL", "numpy", "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick", "PySide6.Qt3DCore",
    "PySide6.Qt3DRender", "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQml", "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets", "PySide6.QtBluetooth", "PySide6.QtNfc", "PySide6.QtPositioning", "PySide6.QtLocation",
    "PySide6.QtSensors", "PySide6.QtSerialPort", "PySide6.QtDesigner", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
    "PySide6.QtDataVisualization", "PySide6.QtGraphs", "PySide6.QtSpatialAudio", "PySide6.QtTextToSpeech",
    "PySide6.QtRemoteObjects", "PySide6.QtScxml", "PySide6.QtHttpServer", "PySide6.QtWebSockets",
]


def analysis(script):
    return Analysis(  # noqa: F821
        [str(Path(SPECPATH) / script)],  # noqa: F821
        pathex=[str(SRC)],
        datas=datas,
        hiddenimports=hidden,
        excludes=EXCLUDES,
        noarchive=False,
        optimize=1,
    )


gui_a = analysis("entry_gui.py")
cli_a = analysis("entry_console.py")
# version resources are generated by scripts/build.ps1 from version_info.template.txt
gui_version = str(Path(SPECPATH) / "version_info_gui.txt")  # noqa: F821
cli_version = str(Path(SPECPATH) / "version_info_console.txt")  # noqa: F821

gui_pyz = PYZ(gui_a.pure)  # noqa: F821
cli_pyz = PYZ(cli_a.pure)  # noqa: F821

gui_exe = EXE(  # noqa: F821
    gui_pyz, gui_a.scripts, [], exclude_binaries=True, name="ArcivoDashboard", console=False, icon=str(BRAND / "arcivo.ico"),
    version=gui_version if Path(gui_version).exists() else None, upx=False,
)
cli_exe = EXE(  # noqa: F821
    cli_pyz, cli_a.scripts, [], exclude_binaries=True, name="Arcivo", console=True, icon=str(BRAND / "arcivo.ico"),
    version=cli_version if Path(cli_version).exists() else None, upx=False,
)
coll = COLLECT(  # noqa: F821
    gui_exe, gui_a.binaries, gui_a.datas,
    cli_exe, cli_a.binaries, cli_a.datas,
    strip=False, upx=False, name="Arcivo",
)
