"""Streaming metadata writers: JSON, JSONL, CSV, TXT, HTML and Markdown."""

from __future__ import annotations

import csv
import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any, TextIO

from .. import APP_NAME, __version__

ALL_FIELDS = [
    "id", "date", "edit_date", "media_type", "category", "text", "file_name", "extension", "mime_type", "file_size",
    "duration", "width", "height", "performer", "audio_title", "sender_id", "sender_name", "sender_username", "chat_id",
    "chat_name", "chat_type", "is_forward", "fwd_date", "fwd_msg_id", "reply_to_id", "grouped_id", "links", "tags",
    "views", "media_id", "dc_id", "exported_file",
]
CONTENT_FIELDS = {"text"}
FORMATS = ["json", "jsonl", "csv", "txt", "html", "md"]


def iso(ts: int | None, tz=None) -> str | None:  # type: ignore[no-untyped-def]
    return datetime.fromtimestamp(ts, tz=tz).isoformat() if ts else None


class Writer:
    ext = "txt"

    def __init__(self, path: Path, fields: list[str], title: str) -> None:
        self.path = path
        self.fields = fields
        self.title = title
        self.fh: TextIO = open(path, "w", encoding="utf-8", newline="")  # noqa: SIM115 (streaming writer, closed in close())
        self.count = 0

    def write(self, rec: dict[str, Any]) -> None:
        raise NotImplementedError

    def close(self) -> None:
        self.fh.close()


class JsonWriter(Writer):
    ext = "json"

    def __init__(self, path: Path, fields: list[str], title: str) -> None:
        super().__init__(path, fields, title)
        meta = {"generator": f"{APP_NAME} {__version__}", "title": title, "exported_at": datetime.now().astimezone().isoformat()}
        self.fh.write('{"meta": ' + json.dumps(meta, ensure_ascii=False) + ', "messages": [\n')

    def write(self, rec: dict[str, Any]) -> None:
        self.fh.write((",\n" if self.count else "") + json.dumps({k: rec.get(k) for k in self.fields}, ensure_ascii=False))
        self.count += 1

    def close(self) -> None:
        self.fh.write("\n]}\n")
        super().close()


class JsonlWriter(Writer):
    ext = "jsonl"

    def write(self, rec: dict[str, Any]) -> None:
        self.fh.write(json.dumps({k: rec.get(k) for k in self.fields}, ensure_ascii=False) + "\n")
        self.count += 1


class CsvWriter(Writer):
    ext = "csv"

    def __init__(self, path: Path, fields: list[str], title: str) -> None:
        super().__init__(path, fields, title)
        self.fh.write("\ufeff")  # BOM so Excel opens UTF-8 (Persian) correctly
        self.w = csv.DictWriter(self.fh, fieldnames=fields, extrasaction="ignore")
        self.w.writeheader()

    def write(self, rec: dict[str, Any]) -> None:
        row = {k: ("; ".join(v) if isinstance(v, list) else v) for k, v in rec.items()}
        # neutralise spreadsheet formula injection
        for k, v in row.items():
            if isinstance(v, str) and v[:1] in ("=", "+", "-", "@"):
                row[k] = "'" + v
        self.w.writerow(row)
        self.count += 1


class TxtWriter(Writer):
    ext = "txt"

    def __init__(self, path: Path, fields: list[str], title: str) -> None:
        super().__init__(path, fields, title)
        self.fh.write(f"{title}\n{'=' * len(title)}\n\n")

    def write(self, rec: dict[str, Any]) -> None:
        head = f"#{rec.get('id')}  {rec.get('date') or ''}  [{rec.get('media_type')}]"
        if rec.get("sender_name"):
            head += f"  — {rec['sender_name']}"
        lines = [head]
        for k in self.fields:
            if k in ("id", "date", "media_type", "sender_name", "text"):
                continue
            v = rec.get(k)
            if v not in (None, "", [], 0, False):
                lines.append(f"  {k}: {'; '.join(v) if isinstance(v, list) else v}")
        if "text" in self.fields and rec.get("text"):
            lines.append("")
            lines.extend("  " + ln for ln in str(rec["text"]).splitlines())
        self.fh.write("\n".join(lines) + "\n\n" + "-" * 60 + "\n\n")
        self.count += 1


class MarkdownWriter(Writer):
    ext = "md"

    def __init__(self, path: Path, fields: list[str], title: str) -> None:
        super().__init__(path, fields, title)
        self.fh.write(f"# {title}\n\n_Generated by {APP_NAME} {__version__}_\n\n")

    def write(self, rec: dict[str, Any]) -> None:
        self.fh.write(f"### #{rec.get('id')} · {rec.get('date') or ''} · `{rec.get('media_type')}`\n\n")
        if rec.get("exported_file"):
            self.fh.write(f"📎 [{rec.get('file_name') or rec['exported_file']}]({rec['exported_file'].replace(' ', '%20')})\n\n")
        if "text" in self.fields and rec.get("text"):
            self.fh.write(str(rec["text"]).replace("\n", "  \n") + "\n\n")
        meta = []
        for k in self.fields:
            v = rec.get(k)
            if k in ("id", "date", "media_type", "text", "exported_file") or v in (None, "", [], False):
                continue
            meta.append(f"**{k}**: {'; '.join(map(str, v)) if isinstance(v, list) else v}")
        if meta:
            self.fh.write(" · ".join(meta) + "\n\n")
        self.fh.write("---\n\n")
        self.count += 1


_HTML_HEAD = """<!doctype html><html lang="{lang}" dir="ltr"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>
:root{{--bg:#0E1116;--card:#161B22;--line:#262D38;--text:#E6EAF0;--muted:#8B95A7;--accent:#7C83FD}}
@media (prefers-color-scheme: light){{:root{{--bg:#F6F7FB;--card:#FFFFFF;--line:#E3E6EE;--text:#1A1F2B;--muted:#5E6878}}}}
body{{margin:0;background:var(--bg);color:var(--text);font:14px/1.6 Inter,"Segoe UI",system-ui,sans-serif}}
header{{padding:28px 32px;border-bottom:1px solid var(--line)}}h1{{margin:0;font-size:22px}}.sub{{color:var(--muted)}}
main{{max-width:980px;margin:0 auto;padding:24px}}.m{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px 18px;margin:0 0 12px}}
.h{{display:flex;gap:10px;flex-wrap:wrap;color:var(--muted);font-size:12px}}.t{{white-space:pre-wrap;margin-top:8px;unicode-bidi:plaintext}}
.badge{{background:color-mix(in srgb,var(--accent) 18%,transparent);color:var(--accent);border-radius:6px;padding:0 8px}}
img.p{{max-width:100%;max-height:360px;border-radius:8px;margin-top:8px}}a{{color:var(--accent)}}dl{{display:grid;grid-template-columns:max-content 1fr;gap:2px 12px;font-size:12px;color:var(--muted);margin:8px 0 0}}
</style></head><body><header><h1>{title}</h1><div class="sub">{subtitle}</div></header><main>
"""


class HtmlWriter(Writer):
    ext = "html"
    IMAGE_EXT = {"jpg", "jpeg", "png", "webp", "gif"}

    def __init__(self, path: Path, fields: list[str], title: str, lang: str = "en") -> None:
        super().__init__(path, fields, title)
        sub = f"{APP_NAME} {__version__} · {datetime.now().astimezone():%Y-%m-%d %H:%M}"
        self.fh.write(_HTML_HEAD.format(lang=lang, title=html.escape(title),
                                        subtitle=html.escape(sub)))

    def write(self, rec: dict[str, Any]) -> None:
        e = html.escape
        parts = [f'<article class="m" id="m{rec.get("id")}"><div class="h"><span class="badge">{e(str(rec.get("media_type")))}</span>'
                 f'<span>#{rec.get("id")}</span><span>{e(str(rec.get("date") or ""))}</span>']
        if rec.get("sender_name"):
            parts.append(f"<span>{e(str(rec['sender_name']))}</span>")
        if rec.get("chat_name"):
            parts.append(f"<span>· {e(str(rec['chat_name']))}</span>")
        parts.append("</div>")
        f = rec.get("exported_file")
        if f:
            href = e(f.replace("\\", "/"))
            if (rec.get("extension") or "").lower() in self.IMAGE_EXT or rec.get("media_type") == "photo":
                parts.append(f'<a href="{href}"><img class="p" loading="lazy" src="{href}" alt=""></a>')
            else:
                parts.append(f'<div>📎 <a href="{href}">{e(str(rec.get("file_name") or f))}</a></div>')
        if "text" in self.fields and rec.get("text"):
            parts.append(f'<div class="t">{e(str(rec["text"]))}</div>')
        meta = [(k, rec.get(k)) for k in self.fields if k not in ("id", "date", "media_type", "text", "sender_name", "chat_name",
                                                                  "exported_file") and rec.get(k) not in (None, "", [], False)]
        if meta:
            items = []
            for k, v in meta:
                if k == "links" and isinstance(v, list):
                    val = " ".join(f'<a href="{e(u)}" rel="noopener">{e(u)}</a>' for u in v)
                else:
                    val = e("; ".join(map(str, v)) if isinstance(v, list) else str(v))
                items.append(f"<dt>{e(k)}</dt><dd>{val}</dd>")
            parts.append("<dl>" + "".join(items) + "</dl>")
        parts.append("</article>\n")
        self.fh.write("".join(parts))
        self.count += 1

    def close(self) -> None:
        self.fh.write(f"</main><footer style='text-align:center;color:var(--muted);padding:24px'>{self.count} messages</footer></body></html>")
        super().close()


WRITERS: dict[str, type[Writer]] = {"json": JsonWriter, "jsonl": JsonlWriter, "csv": CsvWriter, "txt": TxtWriter,
                                    "html": HtmlWriter, "md": MarkdownWriter}


def record_from_row(row: Any, *, links: list[str], tags: list[str], exported_file: str | None, tz=None) -> dict[str, Any]:  # type: ignore[no-untyped-def]
    d = dict(row)
    return {
        "id": d["id"], "date": iso(d.get("date_ts"), tz), "edit_date": iso(d.get("edit_ts"), tz), "media_type": d.get("media_type"),
        "category": d.get("category"), "text": d.get("text") or "", "file_name": d.get("file_name"), "extension": d.get("extension"),
        "mime_type": d.get("mime_type"), "file_size": d.get("file_size"), "duration": d.get("duration"), "width": d.get("width"),
        "height": d.get("height"), "performer": d.get("performer"), "audio_title": d.get("audio_title"),
        "sender_id": d.get("sender_id"), "sender_name": d.get("sender_name"), "sender_username": d.get("sender_username"),
        "chat_id": d.get("chat_id"), "chat_name": d.get("chat_name"), "chat_type": d.get("chat_type"),
        "is_forward": bool(d.get("is_forward")), "fwd_date": iso(d.get("fwd_date_ts"), tz), "fwd_msg_id": d.get("fwd_msg_id"),
        "reply_to_id": d.get("reply_to_id"), "grouped_id": d.get("grouped_id"), "links": links, "tags": tags,
        "views": d.get("views"), "media_id": d.get("media_id"), "dc_id": d.get("dc_id"), "exported_file": exported_file,
    }
